import type { DemoMatch, DemoTeam } from "@/lib/types";

const teams: Record<string, DemoTeam> = {
  mexico: { id: "mexico", name: "México", shortName: "México", flag: "🇲🇽" },
  southAfrica: {
    id: "south-africa",
    name: "África do Sul",
    shortName: "África do Sul",
    flag: "🇿🇦",
  },
  canada: { id: "canada", name: "Canadá", shortName: "Canadá", flag: "🇨🇦" },
  bosnia: {
    id: "bosnia",
    name: "Bósnia e Herzegovina",
    shortName: "Bósnia",
    flag: "🇧🇦",
  },
  brazil: { id: "brazil", name: "Brasil", shortName: "Brasil", flag: "🇧🇷" },
  morocco: {
    id: "morocco",
    name: "Marrocos",
    shortName: "Marrocos",
    flag: "🇲🇦",
  },
  usa: {
    id: "usa",
    name: "Estados Unidos",
    shortName: "Estados Unidos",
    flag: "🇺🇸",
  },
  paraguay: {
    id: "paraguay",
    name: "Paraguai",
    shortName: "Paraguai",
    flag: "🇵🇾",
  },
  france: { id: "france", name: "França", shortName: "França", flag: "🇫🇷" },
  senegal: { id: "senegal", name: "Senegal", shortName: "Senegal", flag: "🇸🇳" },
  argentina: {
    id: "argentina",
    name: "Argentina",
    shortName: "Argentina",
    flag: "🇦🇷",
  },
  algeria: {
    id: "algeria",
    name: "Argélia",
    shortName: "Argélia",
    flag: "🇩🇿",
  },
  portugal: {
    id: "portugal",
    name: "Portugal",
    shortName: "Portugal",
    flag: "🇵🇹",
  },
  colombia: {
    id: "colombia",
    name: "Colômbia",
    shortName: "Colômbia",
    flag: "🇨🇴",
  },
};

export const demoMatches: DemoMatch[] = [
  {
    id: "match-1",
    stage: "group",
    stageLabel: "Grupo A",
    dateLabel: "11 jun",
    timeLabel: "20:00",
    venue: "Estádio Cidade do México",
    locked: false,
    homeTeam: teams.mexico,
    awayTeam: teams.southAfrica,
  },
  {
    id: "match-2",
    stage: "group",
    stageLabel: "Grupo B",
    dateLabel: "12 jun",
    timeLabel: "20:00",
    venue: "Toronto Stadium",
    locked: false,
    homeTeam: teams.canada,
    awayTeam: teams.bosnia,
    prediction: { homeScore: 2, awayScore: 0 },
  },
  {
    id: "match-3",
    stage: "group",
    stageLabel: "Grupo C",
    dateLabel: "13 jun",
    timeLabel: "23:00",
    venue: "New York New Jersey Stadium",
    locked: false,
    homeTeam: teams.brazil,
    awayTeam: teams.morocco,
    prediction: { homeScore: 2, awayScore: 1 },
  },
  {
    id: "match-4",
    stage: "group",
    stageLabel: "Grupo D",
    dateLabel: "12 jun",
    timeLabel: "02:00",
    venue: "Los Angeles Stadium",
    locked: false,
    homeTeam: teams.usa,
    awayTeam: teams.paraguay,
  },
  {
    id: "match-5",
    stage: "group",
    stageLabel: "Grupo I",
    dateLabel: "15 jun",
    timeLabel: "17:00",
    venue: "Boston Stadium",
    locked: false,
    homeTeam: teams.france,
    awayTeam: teams.senegal,
  },
  {
    id: "match-6",
    stage: "group",
    stageLabel: "Grupo J",
    dateLabel: "16 jun",
    timeLabel: "20:00",
    venue: "Kansas City Stadium",
    locked: false,
    homeTeam: teams.argentina,
    awayTeam: teams.algeria,
    prediction: { homeScore: 3, awayScore: 0 },
  },
  {
    id: "match-7",
    stage: "group",
    stageLabel: "Grupo K",
    dateLabel: "18 jun",
    timeLabel: "17:00",
    venue: "Houston Stadium",
    locked: false,
    homeTeam: teams.portugal,
    awayTeam: teams.colombia,
  },
  {
    id: "match-8",
    stage: "group",
    stageLabel: "Grupo C",
    dateLabel: "19 jun",
    timeLabel: "20:00",
    venue: "Philadelphia Stadium",
    locked: true,
    homeTeam: teams.brazil,
    awayTeam: teams.bosnia,
    prediction: { homeScore: 2, awayScore: 0 },
  },
  {
    id: "match-9",
    stage: "final",
    stageLabel: "Final · simulação",
    dateLabel: "19 jul",
    timeLabel: "20:00",
    venue: "New York New Jersey Stadium",
    locked: false,
    homeTeam: teams.brazil,
    awayTeam: teams.argentina,
  },
];

export const demoPools = [
  { id: "family", name: "Família Faysk", flagCode: "br", code: "FYSK26", members: 12, position: 2 },
  { id: "friends", name: "Resenha da Firma", flagCode: "pt", code: "FIRMA7", members: 8, position: 1 },
  { id: "football", name: "Só Quem Entende", flagCode: "ar", code: "BOLA10", members: 6, position: 4 },
];

export const demoRanking = [
  { position: 1, name: "Marina Souza", initials: "MS", points: 72, exact: 4, correct: 11, trend: "—" },
  { position: 2, name: "Faysk", initials: "FY", points: 68, exact: 3, correct: 12, trend: "↑ 1", isCurrentUser: true },
  { position: 3, name: "João Pedro", initials: "JP", points: 63, exact: 3, correct: 10, trend: "↓ 1" },
  { position: 4, name: "Camila Reis", initials: "CR", points: 59, exact: 2, correct: 11, trend: "↑ 2" },
  { position: 5, name: "Rafael Lima", initials: "RL", points: 55, exact: 2, correct: 9, trend: "↓ 1" },
];
