// Generated by scripts/optimize-player-stickers.mjs. Do not edit manually.

export type PlayerStickerAsset = {
  src: string;
  width: number;
  height: number;
};

export const PLAYER_STICKER_ASSETS: Record<string, PlayerStickerAsset> = {
  "player:ALG:7:riyad-karim-mahrez": { src: "/stickers/players/alg-07-mahrez.webp", width: 512, height: 768 },
  "player:ARG:10:lionel-andres-messi": { src: "/stickers/players/arg-10-messi.webp", width: 512, height: 768 },
  "player:ARG:22:lautaro-javier-martinez": { src: "/stickers/players/arg-22-l-martinez.webp", width: 512, height: 768 },
  "player:AUT:7:marko-arnautovic": { src: "/stickers/players/aut-07-arnautovic.webp", width: 512, height: 768 },
  "player:BEL:7:kevin-de-bruyne": { src: "/stickers/players/bel-07-de-bruyne.webp", width: 512, height: 768 },
  "player:BEL:9:romelu-lukaku-bolingoli": { src: "/stickers/players/bel-09-lukaku.webp", width: 512, height: 768 },
  "player:BIH:11:edin-dzeko": { src: "/stickers/players/bih-11-dzeko.webp", width: 512, height: 768 },
  "player:BRA:10:neymar-da-silva-santos-junior": { src: "/stickers/players/bra-10-neymar-jr.webp", width: 512, height: 768 },
  "player:CAN:10:jonathan-christian-david": { src: "/stickers/players/can-10-j-david.webp", width: 512, height: 768 },
  "player:CAN:9:cyle-christopher-larin": { src: "/stickers/players/can-09-larin.webp", width: 512, height: 768 },
  "player:COL:10:james-david-rodriguez-rubio": { src: "/stickers/players/col-10-james.webp", width: 512, height: 768 },
  "player:CRO:10:luka-modric": { src: "/stickers/players/cro-10-modric.webp", width: 512, height: 768 },
  "player:CRO:14:ivan-perisic": { src: "/stickers/players/cro-14-perisic.webp", width: 512, height: 768 },
  "player:CRO:9:andrej-kramaric": { src: "/stickers/players/cro-09-kramaric.webp", width: 512, height: 768 },
  "player:ECU:13:enner-remberto-valencia-lastra": { src: "/stickers/players/ecu-13-e-valencia.webp", width: 512, height: 768 },
  "player:EGY:10:mohamed-salah-hamed-mahrous-ghaly": { src: "/stickers/players/egy-10-m-salah.webp", width: 512, height: 768 },
  "player:ENG:9:harry-edward-kane": { src: "/stickers/players/eng-09-kane.webp", width: 512, height: 768 },
  "player:FRA:10:kylian-mbappe-lottin": { src: "/stickers/players/fra-10-mbappe.webp", width: 512, height: 768 },
  "player:GHA:9:jordan-pierre-ayew": { src: "/stickers/players/gha-09-ayew.webp", width: 512, height: 768 },
  "player:HAI:20:frantzdy-pierrot": { src: "/stickers/players/hai-20-pierrot.webp", width: 512, height: 769 },
  "player:HAI:9:duckens-nazon": { src: "/stickers/players/hai-09-nazon.webp", width: 512, height: 768 },
  "player:IRN:9:mehdi-taremi": { src: "/stickers/players/irn-09-taremi.webp", width: 512, height: 768 },
  "player:IRQ:18:aymen-hussein-ghadhban-ghadhban": { src: "/stickers/players/irq-18-aymen.webp", width: 512, height: 768 },
  "player:KOR:7:heung-min-son": { src: "/stickers/players/kor-07-heungmin.webp", width: 512, height: 768 },
  "player:MAR:20:ayoub-el-kaabi": { src: "/stickers/players/mar-20-el-kaabi.webp", width: 512, height: 768 },
  "player:MEX:9:raul-alonso-jimenez-rodriguez": { src: "/stickers/players/mex-09-raul.webp", width: 512, height: 768 },
  "player:NED:10:memphis-depay": { src: "/stickers/players/ned-10-memphis.webp", width: 512, height: 768 },
  "player:NOR:9:erling-braut-haaland": { src: "/stickers/players/nor-09-braut-haaland.webp", width: 512, height: 769 },
  "player:NZL:9:christopher-grant-wood": { src: "/stickers/players/nzl-09-wood.webp", width: 512, height: 768 },
  "player:POR:7:cristiano-ronaldo-dos-santos-aveiro": { src: "/stickers/players/por-07-ronaldo.webp", width: 512, height: 768 },
  "player:POR:8:bruno-miguel-borges-fernandes": { src: "/stickers/players/por-08-b-fernandes.webp", width: 512, height: 768 },
  "player:QAT:10:hasan-khalid-h-alhaydos": { src: "/stickers/players/qat-10-alhaydos.webp", width: 512, height: 768 },
  "player:QAT:11:akram-hassan-a-y-afif": { src: "/stickers/players/qat-11-afif.webp", width: 512, height: 768 },
  "player:QAT:19:almoez-ali-zainelabdeen-m-abdulla": { src: "/stickers/players/qat-19-almoez.webp", width: 512, height: 768 },
  "player:SEN:10:sadio-mane": { src: "/stickers/players/sen-10-mane.webp", width: 512, height: 768 },
  "player:USA:10:christian-mate-pulisic": { src: "/stickers/players/usa-10-pulisic.webp", width: 512, height: 768 },
  "player:UZB:14:eldor-shomurodov": { src: "/stickers/players/uzb-14-shomurodov.webp", width: 512, height: 768 },
};

export function playerStickerAsset(optionKey: string) {
  return PLAYER_STICKER_ASSETS[optionKey] ?? null;
}
